FROM swift:5.10-jammy as dev

# Install debugging and development tools
RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    && apt-get -q update \
    && apt-get -q install -y \
        lldb \
        vim \
    && rm -rf /var/lib/apt/lists/*

# Create a vapor user and group
RUN useradd --user-group --create-home --system --skel /dev/null --home-dir /app vapor

WORKDIR /app

# Set up owned build/cache dirs
RUN mkdir -p /app/.build /app/.swiftpm /app/.cache && \
    chown -R vapor:vapor /app

# Switch to vapor user
USER vapor

# Copy package files and resolve dependencies
COPY --chown=vapor:vapor Package.swift Package.resolved ./
RUN swift package resolve --skip-update \
    $([ -f ./Package.resolved ] && echo "--force-resolved-versions" || true)

# Copy remaining project files
COPY --chown=vapor:vapor . .

# Run app in dev mode
CMD ["swift", "run", "App", "--", "serve", "--env", "development", "--hostname", "0.0.0.0", "--port", "8080"]
