# ================================
# Development Image
# ================================
FROM swift:5.10-jammy as dev

# Install debugging and development tools
RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    && apt-get -q update \
    && apt-get -q install -y \
        lldb \
        vim \
    && rm -rf /var/lib/apt/lists/*

# Create a vapor user and group
RUN useradd --user-group --create-home --system --skel /dev/null --home-dir /app vapor
RUN chown -R vapor:vapor /app
# USER vapor

# Set working directory
WORKDIR /app

RUN mkdir -p /app/.build && chmod -R 777 /app/.build
RUN mkdir -p ~/.swiftpm && chmod -R 777 ~/.swiftpm
RUN mkdir -p ~/.cache && chmod -R 777 ~/.cache

# Copy dependencies to cache layer
COPY Package.swift Package.resolved ./
RUN swift package resolve --skip-update \
    $([ -f ./Package.resolved ] && echo "--force-resolved-versions" || true)

# Copy the entire project (live updates will be mounted via volumes)
COPY . .

# Run the project in debug mode (hot reload via volumes)
CMD ["swift", "run", "App", "--", "serve", "--env", "development", "--hostname", "0.0.0.0", "--port", "8080"]
